name: Comware Coder Proxy Main CI

permissions: write-all

on:
  push:
    branches: [ ci-*, main ]
    tags: [ pre*, v* ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      commitHash: ${{ steps.git-info.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          COMMIT_HASH=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo "commitHash=$COMMIT_HASH" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./build
      RELEASE_FOLDER: ./release
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      #      - name: Setup vcpkg
      #        uses: lukka/run-vcpkg@v11
      #      - name: CMake Configure and Build
      #        uses: lukka/run-cmake@v10
      #        with:
      #          workflowPreset: ${{ matrix.config }}
      - name: Uninstall Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64
        shell: pwsh
        run: "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vs_installer.exe" modify --norestart --nocache --quiet --installPath "C:/Program Files/Microsoft Visual Studio/2022/Enterprise" --remove "Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64"
      - name: Install Microsoft.VisualStudio.Component.VC.14.39.17.9.x86.x64
        shell: pwsh
        run: "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vs_installer.exe" modify --norestart --nocache --quiet --installPath "C:/Program Files/Microsoft Visual Studio/2022/Enterprise" --add "Microsoft.VisualStudio.Component.VC.14.39.17.9.x86.x64"
      - name: CMake Configure and Build
        run: |
          ls "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/"
          cmake.exe -A Win32 -G "Visual Studio 17 2022" -DCMAKE_VS_PLATFORM_TOOLSET="v143,version=14.39" -DCMAKE_BUILD_TYPE=Release -S "${{ github.workspace }}" -B "${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}"
          cmake.exe --build "${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}" --target msimg32 --config ${{ matrix.config }}
      #      - name: CMake Configure and Build
      #        run: |
      #          ls "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/"
      #          echo "DevEnvDir: ${{ env.DevEnvDir }}"
      #          cmake --workflow --preset ${{ matrix.config }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmw-coder-proxy_${{ needs.get-info.outputs.commitHash }}_${{ GITHUB.RUN_NUMBER }}_${{ matrix.config }}
          path: "${{ env.OUTPUT_FOLDER }}/${{ matrix.config }}"
      - name: Prepare for release
        if: ${{ (startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v')) && matrix.config == 'release'}}
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FOLDER }}
          cp ${{ env.OUTPUT_FOLDER }}/${{ matrix.config }}/msimg32.dll ${{ env.RELEASE_FOLDER }}/loaderdll.dll
          cp ${{ env.OUTPUT_FOLDER }}/${{ matrix.config }}/zlib1.dll ${{ env.RELEASE_FOLDER }}/zlib1.dll
      - name: Upload release
        if: ${{ (startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v')) && matrix.config == 'release'}}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ env.RELEASE_FOLDER }}/loaderdll.dll
            ${{ env.RELEASE_FOLDER }}/zlib1.dll
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre') }}
