name: Comware Coder Proxy Main CI

permissions: write-all

on:
  push:
    branches: [ ci-*, main ]
    tags: [ pre*, v* ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      commitHash: ${{ steps.git-info.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          COMMIT_HASH=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo "commitHash=$COMMIT_HASH" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./build
      RELEASE_FOLDER: ./release
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Get VS Enterprise
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_enterprise.exe" -OutFile "vs_enterprise.exe"
      - name: Install MSVC 14.35
        shell: cmd
        run: |
          vs_enterprise.exe --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --passive --norestart --wait --add Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64
#      - name: Install MSVC 14.35
#        shell: cmd
#        run: |
#          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet --norestart --nocache --add Microsoft.VisualStudio.Component.VC.14.35.17.5.x86.x64
      - name: CMake Configure and Build
        run: |
          ls "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/"
          Add-Content -Path .\vcpkg\triplets\x86-windows.cmake, .\vcpkg\triplets\x64-windows.cmake -Value 'set(VCPKG_PLATFORM_TOOLSET_VERSION "14.35" CACHE STRING "Vcpkg platform toolset version")'
          cmake -G "Visual Studio 17 2022" -A Win32 -T v143,host=x86,version=14.35 -S "${{ github.workspace }}" -B "${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}"
          cmake --build "${{ github.workspace }}/${{ env.OUTPUT_FOLDER }}" --target msimg32 --config ${{ matrix.config }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmw-coder-proxy_${{ needs.get-info.outputs.commitHash }}_${{ GITHUB.RUN_NUMBER }}_${{ matrix.config }}
          path: "${{ env.OUTPUT_FOLDER }}/${{ matrix.config }}"
      - name: Prepare for release
        if: ${{ (startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v')) && matrix.config == 'release'}}
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FOLDER }}
          cp ${{ env.OUTPUT_FOLDER }}/${{ matrix.config }}/*.dll ${{ env.RELEASE_FOLDER }}
          mv ${{ env.RELEASE_FOLDER }}/msimg32.dll ${{ env.RELEASE_FOLDER }}/loaderdll.dll
      - name: Upload release
        if: ${{ (startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v')) && matrix.config == 'release'}}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ env.RELEASE_FOLDER }}/*.dll
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre') }}
