name: Hephaestus Develop CI

on:
  push:
    branches: [ main ]
    tags: [ pre*, v* ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.actual-get-info.outputs.commit }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        id: actual-get-info
        run: echo "::set-output name=commit::$(git rev-parse --short ${{ GITHUB.SHA }})"

  build-windows:
    runs-on: windows-latest
    needs: get-info
    env:
      OUTPUT_FOLDER: ./build
      RELEASE_FOLDER: ./release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
      - name: Configure CMake
        run: cmake -A Win32 -B ${{ env.OUTPUT_FOLDER }} -DCMAKE_BUILD_TYPE=Release
      - name: Build Release
        run: cmake --build ${{ env.OUTPUT_FOLDER }} --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmw-coder-proxy_${{ needs.get-info.outputs.commit }}_${{ GITHUB.RUN_NUMBER }}_Windows
          path: ${{ env.OUTPUT_FOLDER }}
      - name: Prepare for release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          mkdir -p ${{ env.RELEASE_FOLDER }}
          cp ${{ env.OUTPUT_FOLDER }}/msimg32.dll ${{ env.RELEASE_FOLDER }}/loaderdll.dll
          cp ${{ env.OUTPUT_FOLDER }}/zlib1.dll ${{ env.RELEASE_FOLDER }}/zlib1.dll
      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/pre') || startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.RELEASE_FOLDER }}/loaderdll.dll
            ${{ env.RELEASE_FOLDER }}/zlib1.dll
          make_latest: ${{ startsWith(github.ref, 'refs/tags/v') }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre') }}
